sudo: required 
services:
  - docker

before_install:
  - docker build -t sh1sh/docker-react -f Dockerfile.dev .  

script:
  -docker run -e CI=true test sh1sh/docker-react npm run test -- --coverage
